# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basecodeStr <- function(x) {
    .Call('qcdh_basecodeStr', PACKAGE = 'qcdh', x)
}

basecode <- function(x) {
    .Call('qcdh_basecode', PACKAGE = 'qcdh', x)
}

chrnumberc <- function(x) {
    .Call('qcdh_chrnumberc', PACKAGE = 'qcdh', x)
}

collapseGenRcppGen <- function(a, b, collmethod) {
    .Call('qcdh_collapseGenRcppGen', PACKAGE = 'qcdh', a, b, collmethod)
}

collapseGenRcppHap <- function(a1, a2, b1, b2, collmethod) {
    .Call('qcdh_collapseGenRcppHap', PACKAGE = 'qcdh', a1, a2, b1, b2, collmethod)
}

summat <- function(x, y) {
    .Call('qcdh_summat', PACKAGE = 'qcdh', x, y)
}

lmc <- function(yr, Xr) {
    .Call('qcdh_lmc', PACKAGE = 'qcdh', yr, Xr)
}

glmc <- function(yr, Xr, family = "normal", link = "identity") {
    .Call('qcdh_glmc', PACKAGE = 'qcdh', yr, Xr, family, link)
}

